<!DOCTYPE HTML>

<html>
    <head>
        <script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "BlogPosting",
        "mainEntityOfPage": {
             "@type": "WebPage",
             "@id": "\/"
        },
        "articleSection" : "blog",
        "name" : "Self-Organizing Maps",
        "headline" : "Self-Organizing Maps",
        "description" : "body { text-align: justify}  Introduction Self-Organizing Maps (SOM) Self-Organizing Maps first introduce by Teuvo Kohonen. According to the Wiki, Self-Organizing Map (SOM) or self-organizing feature map (SOFM) is a type of artificial neural network (ANN) that is trained using unsupervised learning to produce a low-dimensional (typically two-dimensional), discretized representation of the input space of the training samples, called a map, and is therefore a method to do dimensionality reduction.",
        "inLanguage" : "en",
        "author" : "",
        "creator" : "",
        "publisher": "",
        "accountablePerson" : "",
        "copyrightHolder" : "",
        "copyrightYear" : "2019",
        "datePublished": "2019-04-26 00:00:00 \x2b0000 UTC",
        "dateModified" : "2019-04-26 00:00:00 \x2b0000 UTC",
        "url" : "\/blog\/self-organizing-maps\/",
        "wordCount" : "2701",
        "keywords" : [ "SOM","Clustering","Unsupervised Learning","Machine Learning","Blog" ]
    }
    </script>
        
            
                <title>Self-Organizing Maps</title>
            
        

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="generator" content="Hugo 0.55.4" />
        
  
    
  

  

  <link rel="apple-touch-icon-precomposed" href='/favicon/apple-touch-icon-precomposed.png'>
  <link rel="icon" href='/favicon/favicon.png'>
  
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content='/favicon/mstile.png'>
  <meta name="application-name" content="Algoritma Technical Blog">
  <meta name="msapplication-tooltip" content="To learn more about our approach to data science problems, feel free to hop over to our blog.">
  <meta name="msapplication-config" content='/favicon/ieconfig.xml'>



        
            <meta name="author" content="Inayatus Sholikhah">
        
        
            
                <meta name="description" content="To learn more about our approach to data science problems, feel free to hop over to our blog.">
            
        

        <meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Self-Organizing Maps"/>
<meta name="twitter:description" content="body { text-align: justify}  Introduction Self-Organizing Maps (SOM) Self-Organizing Maps first introduce by Teuvo Kohonen. According to the Wiki, Self-Organizing Map (SOM) or self-organizing feature map (SOFM) is a type of artificial neural network (ANN) that is trained using unsupervised learning to produce a low-dimensional (typically two-dimensional), discretized representation of the input space of the training samples, called a map, and is therefore a method to do dimensionality reduction."/>
<meta name="twitter:site" content="@teamalgoritma"/>

        <meta property="og:title" content="Self-Organizing Maps" />
<meta property="og:description" content="body { text-align: justify}  Introduction Self-Organizing Maps (SOM) Self-Organizing Maps first introduce by Teuvo Kohonen. According to the Wiki, Self-Organizing Map (SOM) or self-organizing feature map (SOFM) is a type of artificial neural network (ANN) that is trained using unsupervised learning to produce a low-dimensional (typically two-dimensional), discretized representation of the input space of the training samples, called a map, and is therefore a method to do dimensionality reduction." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/blog/self-organizing-maps/" />
<meta property="article:published_time" content="2019-04-26T00:00:00&#43;00:00"/>
<meta property="article:modified_time" content="2019-04-26T00:00:00&#43;00:00"/>

        <meta property="og:image" content="//images/logo.png">
        <meta property="og:image:type" content="image/png">
        <meta property="og:image:width" content="512">
        <meta property="og:image:height" content="512">
        
<meta itemprop="name" content="Self-Organizing Maps">
<meta itemprop="description" content="body { text-align: justify}  Introduction Self-Organizing Maps (SOM) Self-Organizing Maps first introduce by Teuvo Kohonen. According to the Wiki, Self-Organizing Map (SOM) or self-organizing feature map (SOFM) is a type of artificial neural network (ANN) that is trained using unsupervised learning to produce a low-dimensional (typically two-dimensional), discretized representation of the input space of the training samples, called a map, and is therefore a method to do dimensionality reduction.">


<meta itemprop="datePublished" content="2019-04-26T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2019-04-26T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="2701">



<meta itemprop="keywords" content="SOM,Clustering,Unsupervised Learning,Machine Learning," />

        

        
            
        

        
        
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800,900|Source+Sans+Pro:400,700">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css">
            <link rel="stylesheet" href="/css/main.css">
            <link rel="stylesheet" href="/css/add-on.css">
            <link rel="stylesheet" href="/css/academicons.min.css">
            <link href="/lib/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
            <link href="/lib/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
            <link href="/lib/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet">
            <link href="/lib/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet">
        

        
            
                
            
                
                    <link rel="stylesheet" href="/css/main.css">
                
            
        


  
    
      <link rel="stylesheet" href="/css/night-owl.css" rel="stylesheet" id="theme-stylesheet">
      <script src="/js/highlight.pack.js"></script>
      <script>hljs.initHighlightingOnLoad();</script>
  


      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-164959107-2', 'auto');
	
	ga('send', 'pageview');
}
</script>






    </head>
    <body>

      
      <div id="wrapper">

    
    
<header id="header">
    
      <h1><a href="/">blog</a></h1>
    

    <nav class="links">
        <ul>
            
                <li>
                    <a href="/">
                            <i class="fa fa-home">&nbsp;</i>Home
                    </a>
                </li>
            
                <li>
                    <a href="/tags/machine-learning/">
                            <i class="fa fa-cog">&nbsp;</i>Machine Learning
                    </a>
                </li>
            
                <li>
                    <a href="/tags/data-visualization/">
                            <i class="fa fa-area-chart">&nbsp;</i>Data Visualization
                    </a>
                </li>
            
                <li>
                    <a href="/tags/">
                            <i class="fa fa-list">&nbsp;</i>Article List
                    </a>
                </li>
            
        </ul>
    </nav>
    <nav class="main">
        <ul>
            
            <li id="share-nav" class="share-menu" style="display:none;">
                <a class="fa-share-alt" href="#share-menu">Share</a>
            </li>
            
            <li class="search">
                <a class="fa-search" href="#search">Search</a>
                <form id="search" method="get" action="//google.com/search">
                    <input type="text" name="q" placeholder="Search" />
                    <input type="hidden" name="as_sitesearch" value="/">
                </form>
            </li>
            <li class="menu">
                <a class="fa-bars" href="#menu">Menu</a>
            </li>
        </ul>
    </nav>
</header>


<section id="menu">

    
        <section>
            <form class="search" method="get" action="//google.com/search">
                <input type="text" name="q" placeholder="Search" />
                <input type="hidden" name="as_sitesearch" value="/">
            </form>
        </section>

    
        <section>
            <ul class="links">
                
                    <li>
                        <a href="/">
                            <h3>
                                <i class="fa fa-home">&nbsp;</i>Home
                            </h3>
                        </a>
                    </li>
                
                    <li>
                        <a href="/tags/machine-learning/">
                            <h3>
                                <i class="fa fa-cog">&nbsp;</i>Machine Learning
                            </h3>
                        </a>
                    </li>
                
                    <li>
                        <a href="/tags/data-visualization/">
                            <h3>
                                <i class="fa fa-area-chart">&nbsp;</i>Data Visualization
                            </h3>
                        </a>
                    </li>
                
                    <li>
                        <a href="/tags/">
                            <h3>
                                <i class="fa fa-list">&nbsp;</i>Article List
                            </h3>
                        </a>
                    </li>
                
            </ul>
        </section>

    
        <section class="recent-posts">
            <div class="mini-posts">
                <header>
                    <h3>Recent Posts</h3>
                </header>
                

                
                    
                

                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/rplicate-i-can-t-get-no/">Rplicate Series: I can&#39;t get no ...</a></h3>
                                
                                <time class="published" datetime=
                                    '2020-10-26'>
                                    October 26, 2020</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/topic-modeling-lda/">Topic Modelling with Latent Dirichlet Allocation (LDA)</a></h3>
                                
                                <time class="published" datetime=
                                    '2020-10-26'>
                                    October 26, 2020</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/one-way-anova-test-in-r/">One-Way ANOVA Test in R</a></h3>
                                
                                <time class="published" datetime=
                                    '2020-10-21'>
                                    October 21, 2020</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/interpreting-black-box-regression-model-with-lime/">Interpreting Black Box Regression Model with LIME</a></h3>
                                
                                <time class="published" datetime=
                                    '2020-10-20'>
                                    October 20, 2020</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/rplicate-series-cherry-bomb/">Rplicate Series: Cherry Bomb</a></h3>
                                
                                <time class="published" datetime=
                                    '2020-10-02'>
                                    October 2, 2020</time>
                            </header>
                            

                        </article>
                

                
                    <a href=
                        
                            /blog/
                        
                        class="button">View more posts</a>
                
            </div>
        </section>

    
        
</section>

    <section id="share-menu">
    <section id="social-share-nav">
        <ul class="links">
            <header>
                <h3>Share this post <i class="fa fa-smile-o"></i></h3>
            </header>
            



<li>
  <a href="https://twitter.com/intent/tweet?text=Self-Organizing%20Maps by Inayatus%20Sholikhah&amp;url=%2fblog%2fself-organizing-maps%2f" target="_blank" class="share-btn twitter">
    <i class="fa fa-twitter"></i>
    <p>Twitter</p>
    </a>
</li>








<li>
  <a href="https://www.facebook.com/sharer.php?u=%2fblog%2fself-organizing-maps%2f" target="_blank" class="share-btn facebook">
    <i class="fa fa-facebook"></i>
    <p>Facebook</p>
    </a>
</li>







<li>
  <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fblog%2fself-organizing-maps%2f&amp;title=Self-Organizing%20Maps" target="_blank" class="share-btn linkedin">
      <i class="fa fa-linkedin"></i>
      <p>LinkedIn</p>
    </a>
</li>











        </ul>
    </section>
</section>

    
    <div id="main">
        
        
        <article class="post">
  <header>
    <div class="title">
        
            <h2><a href="/blog/self-organizing-maps/">Self-Organizing Maps</a></h2>
        
        
    </div>
    <div class="meta">
        

        <time class="published"
            datetime='2019-04-26'>
            April 26, 2019</time>
        <span class="author"><a href="https://github.com/inytss">Inayatus Sholikhah</a></span>
        
            <p>13 minute read</p>
        
        
    </div>
</header>


  
    <section id="social-share">
      <ul class="icons">
        



<li>
  <a href="https://twitter.com/intent/tweet?text=Self-Organizing%20Maps by Inayatus%20Sholikhah&amp;url=%2fblog%2fself-organizing-maps%2f" target="_blank" class="share-btn twitter">
    <i class="fa fa-twitter"></i>
    <p>Twitter</p>
    </a>
</li>








<li>
  <a href="https://www.facebook.com/sharer.php?u=%2fblog%2fself-organizing-maps%2f" target="_blank" class="share-btn facebook">
    <i class="fa fa-facebook"></i>
    <p>Facebook</p>
    </a>
</li>







<li>
  <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fblog%2fself-organizing-maps%2f&amp;title=Self-Organizing%20Maps" target="_blank" class="share-btn linkedin">
      <i class="fa fa-linkedin"></i>
      <p>LinkedIn</p>
    </a>
</li>











      </ul>
    </section>
  

  
    

    
        
        







  
  
    
  


        
        
        

        <a href="/blog/self-organizing-maps/" class="image featured">
            <img src="/img/2019/04/Algotech_Post_Self_Organizing_Map.png" alt="">
        </a>
    


  <div id="content">
    

<style>
body {
text-align: justify}
</style>

<h1 id="introduction-self-organizing-maps-som">Introduction Self-Organizing Maps (SOM)</h1>

<p>Self-Organizing Maps first introduce by Teuvo Kohonen. According to the Wiki, Self-Organizing Map (SOM) or self-organizing feature map (SOFM) is a type of artificial neural network (ANN) that is trained using unsupervised learning to produce a low-dimensional (typically two-dimensional), discretized representation of the input space of the training samples, called a map, and is therefore a method to do dimensionality reduction.<sup class="footnote-ref" id="fnref:1"><a href="#fn:1">1</a></sup> SOM isan unsupervised data visualization technique that can be used to visualize high-dimensional data sets in lower (typically 2) dimensional representations.<sup class="footnote-ref" id="fnref:2"><a href="#fn:2">2</a></sup> SOM also represent clustering concept by groupingsimilar features together. So, SOM can use to cluster high-dimensional data sets by doing dimensionality reduction and visualize it using maps.</p>

<p><center> <img src="/img/som/arsitektur.PNG"> </center></p>

<p>Each data point in the data set recognizes themselves by competing for representation. SOM mapping steps startfrom initializing the weight vectors. From there a sample vector is selected randomly and the map of weight vectors is searched to find which weight best represents that sample. Each weight vector has neighborhood weights that are close to it. The weight that is chosen is rewarded by being able to become more like that randomly selected sample vector. The neighbors of that weight are also rewarded by being able to become more like the chosen sample vector. This allows the map to grow and form different shapes. Most generally, they form square/rectangular/hexagonal/L shapes in the 2D feature space.</p>

<p>SOM calculatesthe distance of each input vector by each weight of nodes. The distance that usually used is Euclidean distance.</p>

<p><strong>This how SOM algorithm work :<sup class="footnote-ref" id="fnref:3"><a href="#fn:3">3</a></sup></strong></p>

<ol>
<li>Preparing input data for training data sets.</li>
<li>Each node’s weights are initialized. A vector is chosen at random from the set of training data.</li>
<li>Calculate the distance of each node. The winning node is commonly known as theBest Matching Unit (BMU).</li>
<li>Updating of weight, then calculate again which one’s weights are most like the input vectors.</li>
<li>Every BMU has a neighbor then calculated. The amount of neighbor is decreasedover time.</li>
<li>The winning weight is rewarded with becoming more like the sample vector. The neighbors also become more like the sample vector. The closer a node is to the BMU, the more its weights get altered and the farther away the neighbor is from the BMU, the less it learns.</li>
<li>Repeat the 2-5 step until every node getting close to input vectors.</li>
</ol>

<p><center> <img src="/img/som/som-training.png"> </center></p>

<p><strong>There are a lot of use case that implement SOM algorithm :<sup class="footnote-ref" id="fnref:4"><a href="#fn:4">4</a></sup></strong></p>

<ol>
<li>Customer segmentation</li>
<li>Fantasy league analysis</li>
<li>Cyber profilling criminals</li>
<li>Identifying crime</li>
<li>etc.</li>
</ol>

<h1 id="som-analysis">SOM Analysis</h1>

<p>In this article, we want to use web analytics dataset in San Francisco. We want to learn <em>how to use SOM to identify characteristics of each cluster</em> in many webs on San Francisco by some features.</p>

<h2 id="library-used">Library Used</h2>

<p>In this article, we used <code>kohonen</code> package for making a SOM algorithm. Since we know that <code>kohonen</code> packages are from <code>class</code>, we use it to make many key function such as :</p>

<ul>
<li><code>somgrid()</code> : initialized SOM node-set</li>
<li><code>som()</code> : making a SOM model, change the radius of neighbourhood, learning rate, and iteration</li>
<li><code>plot.kohonen()</code> / <code>plot()</code> : visualization of resulting SOM</li>
</ul>

<pre><code class="language-r">library(kohonen)
library(dplyr)
</code></pre>

<p>In this article, we want to use <code>ads data</code> from xyz company that makes ads on Facebook.</p>

<h2 id="data-pre-processing">Data Pre-Processing</h2>

<p>First of all we want to import the data in this workspace.</p>

<pre><code class="language-r">ads &lt;- read.csv(&quot;data_input/KAG_conversion_data.csv&quot;) %&gt;% 
  glimpse()
</code></pre>

<pre><code>#&gt; Observations: 1,143
#&gt; Variables: 11
#&gt; $ ad_id               &lt;int&gt; 708746, 708749, 708771, 708815, 708818, 708820,...
#&gt; $ xyz_campaign_id     &lt;int&gt; 916, 916, 916, 916, 916, 916, 916, 916, 916, 91...
#&gt; $ fb_campaign_id      &lt;int&gt; 103916, 103917, 103920, 103928, 103928, 103929,...
#&gt; $ age                 &lt;fct&gt; 30-34, 30-34, 30-34, 30-34, 30-34, 30-34, 30-34...
#&gt; $ gender              &lt;fct&gt; M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, M,...
#&gt; $ interest            &lt;int&gt; 15, 16, 20, 28, 28, 29, 15, 16, 27, 28, 31, 7, ...
#&gt; $ Impressions         &lt;int&gt; 7350, 17861, 693, 4259, 4133, 1915, 15615, 1095...
#&gt; $ Clicks              &lt;int&gt; 1, 2, 0, 1, 1, 0, 3, 1, 1, 3, 0, 0, 0, 0, 7, 0,...
#&gt; $ Spent               &lt;dbl&gt; 1.43, 1.82, 0.00, 1.25, 1.29, 0.00, 4.77, 1.27,...
#&gt; $ Total_Conversion    &lt;int&gt; 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
#&gt; $ Approved_Conversion &lt;int&gt; 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,...
</code></pre>

<ul>
<li><code>ad_id</code> : an unique ID of each ad</li>
<li><code>xyz_campaign_id</code> : an ID associated with each ad campaign of XYZ company</li>
<li><code>fb_campaign_id</code> : an ID associated with how Facebook tracks each campaign</li>
<li><code>age</code> : age of the person to whom the ad is shown</li>
<li><code>gender</code> : gender of the person to whon thw ad si shown</li>
<li><code>interest</code> : a code specifying the category to which the person’s interest belongs (interests are as mentioned in the person’s Facebook public profile)</li>
<li><code>Impressions</code> : number of time the ad is shown</li>
<li><code>Clicks</code> : number od click on for the ad</li>
<li><code>Spent</code> : amount paid from xyz company to Facebook to shown the ad</li>
<li><code>Total_Conversion</code> : total number of people who enquired about the product after seeing the ad</li>
<li><code>approved_Conversion</code> : total number of people who bougth the product after seeing the ad</li>
</ul>

<pre><code class="language-r">ads &lt;- ads %&gt;% 
  mutate(ad_id = as.factor(ad_id),
         xyz_campaign_id = as.factor(xyz_campaign_id),
         fb_campaign_id = as.factor(fb_campaign_id))

levels(ads$xyz_campaign_id)
</code></pre>

<pre><code>#&gt; [1] &quot;916&quot;  &quot;936&quot;  &quot;1178&quot;
</code></pre>

<p>As we know that if SOM used numerical data, so if we have categorical variables we must to change those variables to dummy variables.</p>

<pre><code class="language-r"># change the chategoric variables to a dummy variables
ads.s &lt;- ads %&gt;% 
  mutate(genderM = ifelse(gender == &quot;M&quot;, 1, 0),
         age2 = ifelse(age == &quot;35-39&quot;, 1, 0),
         age3 = ifelse(age == &quot;40-44&quot;, 1, 0),
         age4 = ifelse(age == &quot;45-49&quot;, 1, 0)) %&gt;% 
  select(-c(1,3:5))

# make a train data sets that scaled and convert them to be a matrix cause kohonen function accept numeric matrix
ads.train &lt;- as.matrix(scale(ads.s[,-1]))
</code></pre>

<p>We have dummy variables, then we make a SOM grid in order to make dimentioanlity reduction from our data.</p>

<pre><code class="language-r"># make stable sampling
RNGkind(sample.kind = &quot;Rounding&quot;)
# make a SOM grid
set.seed(100)
ads.grid &lt;- somgrid(xdim = 10, ydim = 10, topo = &quot;hexagonal&quot;)

# make a SOM model
set.seed(100)
ads.model &lt;- som(ads.train, ads.grid, rlen = 500, radius = 2.5, keep.data = TRUE,
                  dist.fcts = &quot;euclidean&quot;)
# str(ads.model)
</code></pre>

<p>From that summary of <code>ads.model</code> we know that our SOM grid has 10x10 dimension.</p>

<h1 id="unsupervised-som">Unsupervised SOM</h1>

<h2 id="visualize-of-som-tabset-tabset-fade-tabset-pills">Visualize of SOM {.tabset .tabset-fade .tabset-pills}</h2>

<p>Before visualizingSOM model, let’s explore a list of SOM model. If we want to know that our data position in maps, we look it in <code>unit.classif</code>. Each value represent the node number to which this application belongs. For example, in the first value of the application, 12 means that in the first application has been classified into 12 particular node.</p>

<pre><code class="language-r">head(ads.model$unit.classif)
</code></pre>

<pre><code>#&gt; [1] 12 13 13 23 22 22
</code></pre>

<p>And we can see the classification of each nodes by codes plot and we can see the values of each nodes using the mapping plot.</p>

<pre><code class="language-r">plot(ads.model, type = &quot;mapping&quot;, pchs = 19, shape = &quot;round&quot;)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-8-1.png" width="2880" style="display: block; margin: auto;" /></p>

<pre><code class="language-r">head(data.frame(ads.train), 5)
</code></pre>

<pre><code>#&gt;     interest Impressions     Clicks      Spent Total_Conversion
#&gt; 1 -0.6591837  -0.5735416 -0.5693235 -0.5745204       -0.1908387
#&gt; 2 -0.6220808  -0.5399346 -0.5517465 -0.5700329       -0.1908387
#&gt; 3 -0.4736696  -0.5948262 -0.5869005 -0.5909745       -0.4138741
#&gt; 4 -0.1768470  -0.5834245 -0.5693235 -0.5765915       -0.4138741
#&gt; 5 -0.1768470  -0.5838274 -0.5693235 -0.5761313       -0.4138741
#&gt;   Approved_Conversion   genderM       age2       age3       age4
#&gt; 1          0.03222233 0.9643282 -0.5261678 -0.4742188 -0.5410454
#&gt; 2         -0.54324835 0.9643282 -0.5261678 -0.4742188 -0.5410454
#&gt; 3         -0.54324835 0.9643282 -0.5261678 -0.4742188 -0.5410454
#&gt; 4         -0.54324835 0.9643282 -0.5261678 -0.4742188 -0.5410454
#&gt; 5          0.03222233 0.9643282 -0.5261678 -0.4742188 -0.5410454
</code></pre>

<pre><code class="language-r">plot(ads.model, type = &quot;codes&quot;, main = &quot;Codes Plot&quot;, palette.name = rainbow)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-10-1.png" width="3360" style="display: block; margin: auto;" /></p>

<p>At the first node, we can say that the input data entered on the first node is characterized bythe major variable that hasgender M and age range of 30-34. For the second node,there is characterized by major variables that have gender M and age range 30-34. Here we can conclude that the node will have neighbors that have similar characteristics to it, that is, like nodes 1 and 2 that are close together because they have gender M and an age range of 30-34 that same.</p>

<h3 id="training-progress">Training Progress</h3>

<p>As the SOM training iterations progress, the distance from each node’s weights to the samples represented by that node is reduced. Ideally, this distance should reach a minimum of plateau. This plot option shows progress over time. If the curve is continually decreasing, more iterations are required.<sup class="footnote-ref" id="fnref:5"><a href="#fn:5">5</a></sup></p>

<pre><code class="language-r">plot(ads.model, type = &quot;changes&quot;)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>

<h3 id="node-counts">Node Counts</h3>

<p>The Kohonen package allows us to visualize the count of how many samples are mapped to each node on the map. This metric can be used as a measure of map quality–ideally, the sample distribution is relatively uniform. Large values in some map areas suggest that a larger map would be beneficial. Empty nodes indicate that your map size is too big for the number of samples. Aim for at least 5-10 samples per node when choosing map size.</p>

<pre><code class="language-r">plot(ads.model, type = &quot;counts&quot;)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-12-1.png" width="2880" style="display: block; margin: auto;" /></p>

<p>Nodes that colored by red mean nodes that have the least number of input values, such as in the second nodes. If the color nodes are brighter indicating the nodes have a lot of input values, such as in the 31 nodes. For nodes that have gray colors, that means the nodes do not have input values at all.</p>

<h3 id="neighbours-nodes">Neighbours Nodes</h3>

<p>If we want to see nodes that have the closest or farthest neighbors, we can plot a plot based on <code>dist.neighbours</code>. Nodes that have darker colors mean that the nodes have a closer vector input, whereas nodes that have lighter colors mean that the nodes have vector inputs that are farther apart.</p>

<pre><code class="language-r">plot(ads.model, type = &quot;dist.neighbours&quot;)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-13-1.png" width="2880" style="display: block; margin: auto;" /></p>

<h3 id="heatmaps">Heatmaps</h3>

<p>Heatmaps are perhaps the most important visualization possible for Self-Organising Maps. A SOM heatmap allows the visualization of the distribution of a single variable across the map. Typically, a SOM investigative process involves the creation of multiple heatmaps and then the comparison of these heatmaps to identify interesting areas on the map. It is important to remember that the individual sample positions do not move from one visualization to another, the map is simply colored by different variables.</p>

<p>The default Kohonen heatmap is created by using the type “heatmap”, and then providing one of the variables from the set of node weights. In this case, we visualize the average education level on the SOM.</p>

<p>The default Kohonen heatmap is created by using the type “heatmap”, and then providing one of the variables from the set of node weights. In this case, we visualize the average education level on the SOM.</p>

<pre><code class="language-r">heatmap.som &lt;- function(model){
  for (i in 1:10) {
  plot(model, type = &quot;property&quot;, property = getCodes(model)[,i], 
        main = colnames(getCodes(model))[i]) 
  }
}
heatmap.som(ads.model)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-1.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-2.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-3.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-4.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-5.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-6.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-7.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-8.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-9.png" width="2880" style="display: block; margin: auto;" /><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-14-10.png" width="2880" style="display: block; margin: auto;" /></p>

<p>From the heatmap that is formed, we can know which nodes have the characteristics of each variablewhose value is high and the value is low.</p>

<h3 id="clustering">Clustering</h3>

<p>Then we want to try to clustering every observation that we have without looking at the labels of <code>xyz_campaign_id</code>. Like making clusters using k-means, we must determine the number of cluster that we want tomake. In this case, we want to use the elbow method to determine the number of clusters.</p>

<pre><code class="language-r">library(factoextra)
set.seed(100)
fviz_nbclust(ads.model$codes[[1]], kmeans, method = &quot;wss&quot;)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-15-1.png" width="2880" style="display: block; margin: auto;" /></p>

<pre><code class="language-r">set.seed(100)
clust &lt;- kmeans(ads.model$codes[[1]], 6)

# clustering using hierarchial
# cluster.som &lt;- cutree(hclust(dist(ads.model$codes[[1]])), 6)
</code></pre>

<pre><code class="language-r">plot(ads.model, type = &quot;codes&quot;, bgcol = rainbow(9)[clust$cluster], main = &quot;Cluster Map&quot;)
add.cluster.boundaries(ads.model, clust$cluster)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-16-1.png" width="3360" style="display: block; margin: auto;" /></p>

<p>At this part, to do the profiling of the clusters that we made, we do not need to look at the descriptive results of the cluster or look deeper into the data, we only need to look at the cluster map above.</p>

<p>The characteristics for each cluster :</p>

<ul>
<li>Cluster 1 (red) : gender Male, age 30-34</li>
<li>Cluster 2 (orange) : gender Female, gender Male, age 40-44, interest middle</li>
<li>Cluster 3 (green light) : gender Female, gender Male,  age 45-49, interest high, impression middle, clicks middle</li>
<li>Cluster 4 (green) : interest high, impression high, clicks high, spent high, gender Male, age 30-34, total conversion high, approved conversion high</li>
<li>Cluster 5 (turqois) : gender Male, age 45-49, interest high, clicks and spent low</li>
<li>Cluster 6 (blue) : gender Female, age 45-49, interest, impression, clicks, spent, total_conversion low.</li>
</ul>

<pre><code class="language-r"># know cluster each data
ads.cluster &lt;- data.frame(ads.s, cluster = clust$cluster[ads.model$unit.classif])
tail(ads.cluster, 10)
</code></pre>

<pre><code>#&gt;      xyz_campaign_id interest Impressions Clicks  Spent Total_Conversion
#&gt; 1134            1178      104      558666    110 162.64               14
#&gt; 1135            1178      105     1118200    235 333.75               11
#&gt; 1136            1178      106      107100     23  33.71                1
#&gt; 1137            1178      107      877769    160 232.59               13
#&gt; 1138            1178      108      212508     33  47.69                4
#&gt; 1139            1178      109     1129773    252 358.19               13
#&gt; 1140            1178      110      637549    120 173.88                3
#&gt; 1141            1178      111      151531     28  40.29                2
#&gt; 1142            1178      113      790253    135 198.71                8
#&gt; 1143            1178      114      513161    114 165.61                5
#&gt;      Approved_Conversion genderM age2 age3 age4 cluster
#&gt; 1134                   5       0    0    0    1       5
#&gt; 1135                   4       0    0    0    1       4
#&gt; 1136                   0       0    0    0    1       5
#&gt; 1137                   4       0    0    0    1       4
#&gt; 1138                   1       0    0    0    1       5
#&gt; 1139                   2       0    0    0    1       4
#&gt; 1140                   0       0    0    0    1       5
#&gt; 1141                   0       0    0    0    1       5
#&gt; 1142                   2       0    0    0    1       5
#&gt; 1143                   2       0    0    0    1       5
</code></pre>

<h1 id="supervised-som">Supervised SOM</h1>

<p>In supervised SOM, we want to classify our SOM model with our dependent variable (<code>xyz_campaign_id</code>). In classification case, we have to do split train-test data in order to ensure our model is good enough to predict other data pattern. First, we split our data to train-test and do a scaling step to make the range of data same.</p>

<pre><code class="language-r"># split data
set.seed(100)
int &lt;- sample(nrow(ads.s), nrow(ads.s)*0.8)
train &lt;- ads.s[int,]
test &lt;- ads.s[-int,]

# scaling data
trainX &lt;- scale(train[,-1])
testX &lt;- scale(test[,-1], center = attr(trainX, &quot;scaled:center&quot;))
</code></pre>

<p>After we have done in train-test split, we make a label for our target variable.</p>

<pre><code class="language-r"># make label
train.label &lt;- factor(train[,1])
test.label &lt;- factor(test[,1])
test[,1] &lt;- 916
testXY &lt;- list(independent = testX, dependent = test.label)
</code></pre>

<h2 id="classification">Classification</h2>

<p>To make an classification model implementing SOM algorithm, we can use <code>xyf()</code> function.</p>

<pre><code class="language-r"># classification &amp; predict
set.seed(100)
class &lt;- xyf(trainX, classvec2classmat(train.label), ads.grid, rlen = 500)
</code></pre>

<p>We can plot the classification result by the type <code>change</code>.</p>

<pre><code class="language-r">plot(class, type = &quot;changes&quot;)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>

<p><code>Matrix 1</code> shows iteration of training progress of real data and the <code>Matrix 2</code> shows iteration of training progress in predict data.</p>

<h2 id="predict">Predict</h2>

<p>To make sure our model is fit enough, we predict our test data <code>testXY</code> using <code>class</code> model. We got the confusion matrix of the prediction. In this data, we get 100% accuracy to predict each class.</p>

<pre><code class="language-r">pred &lt;- predict(class, newdata = testXY)
table(Predict = pred$predictions[[2]], Actual = test.label)
</code></pre>

<pre><code>#&gt;        Actual
#&gt; Predict 916 936 1178
#&gt;    916   14   0    0
#&gt;    936    0 101    0
#&gt;    1178   0   0  114
</code></pre>

<h2 id="cluster-boundaries">Cluster Boundaries</h2>

<p>We can visualize each class by each cluster using cluster boundaries.</p>

<pre><code class="language-r">plot(ads.model, type = &quot;codes&quot;, bgcol = rainbow(9)[clust$cluster], main = &quot;Cluster SOM&quot;)
add.cluster.boundaries(ads.model, clust$cluster)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-23-1.png" width="2880" style="display: block; margin: auto;" /></p>

<p>To ensure our classification prediction and each cluster, we can see the visualization of each class and each cluster using cluster bounderies.</p>

<pre><code class="language-r">c.class &lt;- kmeans(class$codes[[2]], 3)
par(mfrow = c(1,2))
plot(class, type = &quot;codes&quot;, main = c(&quot;Unsupervised SOM&quot;, &quot;Supervised SOM&quot;), 
     bgcol = rainbow(3)[c.class$cluster])
add.cluster.boundaries(class, c.class$cluster)
</code></pre>

<p><img src="/blog/2019-04-26-self-organizing-maps_files/figure-html/unnamed-chunk-24-1.png" width="2880" style="display: block; margin: auto;" /></p>

<h1 id="conclusion">Conclusion</h1>

<ul>
<li>From the results of SOM clustering using unsupervised and supervised, we can conclude that for <code>xyz_campaign_id</code> 916 more interested in the ads displayed are Male and Female aged 30-49 and they are interested in existing ads and then make payments after seeing the ads.</li>
<li>For <code>xyz_campaign_id</code> 936, those who see the ads is Male and Female in ranging age from 30-39 and they are only interested in the ads that are displayed but to make payments after seeing the ads are small.</li>
<li>For <code>xyz_campaign_id</code> 1178, which saw moreads for femalesand aged 30-34 years.</li>
</ul>

<p>There are pros and cons using this algorithm. <em>The advantage using SOM :</em></p>

<ul>
<li>Intuitive method to develop profilling</li>
<li>Easy to explain the result with the maps</li>
<li>Can visualize high-dimensional data by two-dimensional maps</li>
</ul>

<p><em>The disadvantage using SOM :</em></p>

<ul>
<li>Requires clean, numeric data</li>
</ul>

<h1 id="annotation">Annotation</h1>
<div class="footnotes">

<hr />

<ol>
<li id="fn:1"><a href="https://en.wikipedia.org/wiki/Self-organizing_map">Wikipedia. Self-organizing Maps.</a>
 <a class="footnote-return" href="#fnref:1"><sup>[return]</sup></a></li>
<li id="fn:2"><a href="https://towardsdatascience.com/self-organizing-maps-ff5853a118d4">Ralhan, A. 2018. <em>Self Organizing Maps</em>.</a>
 <a class="footnote-return" href="#fnref:2"><sup>[return]</sup></a></li>
<li id="fn:3"><a href="https://www.shanelynn.ie/self-organising-maps-for-customer-segmentation-using-r/">Lynn, Shane. Self-Organizing Maps for Customer Segementation using R.</a>
 <a class="footnote-return" href="#fnref:3"><sup>[return]</sup></a></li>
<li id="fn:4"><a href="https://www.superdatascience.com/blogs/self-organizing-maps-soms-how-do-self-organizing-maps-learn-part-1/">Self Organizing Maps</a>
 <a class="footnote-return" href="#fnref:4"><sup>[return]</sup></a></li>
<li id="fn:5"><a href="https://www.superdatascience.com/blogs/the-ultimate-guide-to-self-organizing-maps-soms">The Ultimate Guide to Self Organizing Maps (SOMs)</a>
 <a class="footnote-return" href="#fnref:5"><sup>[return]</sup></a></li>
</ol>
</div>

  </div>

  <footer>
    <ul class="stats">
  <li class="categories">
    <ul>
        
            
            
                <i class="fa fa-folder"></i>
                
                
                <li><a class="article-category-link" href="/categories/r">R</a></li>
                
            
        
    </ul>
  </li>
  <li class="tags">
    <ul>
        
            
            
                <i class="fa fa-tags"></i>
                
                
                <li><a class="article-category-link" href="/tags/som">SOM</a></li>
                
                
                <li><a class="article-category-link" href="/tags/clustering">Clustering</a></li>
                
                
                <li><a class="article-category-link" href="/tags/unsupervised-learning">Unsupervised Learning</a></li>
                
                
                <li><a class="article-category-link" href="/tags/machine-learning">Machine Learning</a></li>
                
            
        
    </ul>
  </li>
</ul>

  </footer>

</article>

    <article class="post">
        <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "https-algotech-netlify-com" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </article>


<ul class="actions pagination">
    
        <li><a href="/blog/age-period-cohort-apc-analysis/"
                class="button big previous">Age-Period-Cohort (APC) Analysis</a></li>
    

    
        <li><a href="/blog/creating-choropleth-with-mapshaper-and-r/"
                class="button big next">Creating Choropleth with Mapshaper and R</a></li>
    
</ul>


    </div>
    
<section id="sidebar">

  
  <section id="intro">
    
    
      
        <a href='/'><img src="/img/main/logo.png" class="intro-circle" width="30%" alt="Hugo Future Imperfect" /></a>
      
    
    
      <header>
        <h2>Algoritma Technical Blog</h2>
        <p>We're a group of people who teach data science to individuals, trains companies and their employees to better profit from data. We care about the development of data science and a sense of community that connects our alumni and team with one another. To learn more about our approach to data science problems, feel free to hop over to our blog.</p>
      </header>
    
    
      <ul class="icons">
        
        
  <li><a href="//github.com/teamalgoritma" target="_blank" title="GitHub" class="fa fa-github"></a></li>



























  <li><a href="//linkedin.com/company/teamalgoritma" target="_blank" title="LinkedIn Company" class="fa fa-linkedin"></a></li>









  <li><a href="//facebook.com/teamalgoritma" target="_blank" title="Facebook" class="fa fa-facebook"></a></li>





















  <li><a href="//instagram.com/teamalgoritma" target="_blank" title="Instagram" class="fa fa-instagram"></a></li>





  <li><a href="//twitter.com/teamalgoritma" target="_blank" title="Twitter" class="fa fa-twitter"></a></li>




















      </ul>
    
  </section>

  
  <section class="recent-posts">
    <div class="mini-posts">
      <header>
        <h3>Upcoming Workshop</h3>
      </header>
      <div class="posts-container">
          <article class="mini-post">
            <header>
              <h3>
                
                                <img src="/img/2020/ads/dss.png", alt="alternatetext", width="270" height="340">
                <a href="https://algorit.ma/text-analysis/?utm_source=algotech">More details</a>
                
                <img src="/img/2020/ads/ddt.png", alt="alternatetext", width="270" height="340">
                <a href="https://algorit.ma/data-driven-2/?utm_source=algotech">More details</a>
              </h3>
            </header>
          </article>
      </div>

      
      
    </div>
  </section>

  
  
  

  
  

  
  <section id="footer">
    <p class="copyright">
      
        &copy; 2020
        
          Algoritma Technical Blog
        
      .
      Powered by <a href="//gohugo.io" target="_blank">Hugo</a>
    </p>
  </section>
</section>

    </div>
    <a id="back-to-top" href="#" class="fa fa-arrow-up fa-border fa-2x"></a>
    <style>
      .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        height:50px; 
        background-color: black;
        color: white;
        text-align: center;
        padding-top: 15px;
        padding-bottom: 15px;
        padding-left: 50px;
        padding-right: 50px;
}
      }


      </style>

      <div class="footer">
        <p>
          Want to know more about our workshop?
          <a href="https://algorit.ma/?utm_source=algotech&utm_medium=content&utm_campaign=self-organizing-maps" style="color: rgb(197, 38, 38)"> Visit our main website here</a> <br>
        </p>
          
      </div>
    

    
      
    

    
      
      
      
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>
        
        
        
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/r.min.js"></script>
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/yaml.min.js"></script>
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/css.min.js"></script>
        <script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>
      
    
    
    
      <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/skel/3.0.1/skel.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js"></script>
      <script src="/js/util.js"></script>
      <script src="/js/main.js"></script>
      <script src="/js/backToTop.js"></script>
    

    
      
        
      
        
          <script src="/js/bootstrap.min.js"></script>
        
      
    

    
    <script>hljs.initHighlightingOnLoad();</script>
      <script src="//yihui.name/js/math-code.js"></script>
<script async
src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>


  </body>
</html>

