<!DOCTYPE HTML>

<html>
    <head>
        <script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "BlogPosting",
        "mainEntityOfPage": {
             "@type": "WebPage",
             "@id": "\/"
        },
        "articleSection" : "blog",
        "name" : "Poisson Regression and Negative Binomial Regression",
        "headline" : "Poisson Regression and Negative Binomial Regression",
        "description" : "Introduction Regression analysis is a set of statistical processes for estimating the relationships among variables. It includes many techniques for modeling and analyzing several variables, when the focus is on the relationship between a dependent variable and one or more independent variables (or \x26lsquo;predictors\x26rsquo;).\nFor example  Find out the effect of land area and building area on house prices in the Kuningan region (Multiple Linear Regression)\n Find out the effect of allowance and GPA on cum laude predicate (yes or no) ?",
        "inLanguage" : "en",
        "author" : "",
        "creator" : "",
        "publisher": "",
        "accountablePerson" : "",
        "copyrightHolder" : "",
        "copyrightYear" : "2019",
        "datePublished": "2019-10-22 00:00:00 \x2b0000 UTC",
        "dateModified" : "2019-10-22 00:00:00 \x2b0000 UTC",
        "url" : "\/blog\/poisson-regression-and-neg-ative-binomial-regression\/",
        "wordCount" : "3108",
        "keywords" : [ "Machine Learning","Blog" ]
    }
    </script>
        
            
                <title>Poisson Regression and Negative Binomial Regression</title>
            
        

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="generator" content="Hugo 0.55.4" />
        


        
            <meta name="author" content="Hafizah Ilma">
        
        
            
                <meta name="description" content="HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo">
            
        

        <meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Poisson Regression and Negative Binomial Regression"/>
<meta name="twitter:description" content="Introduction Regression analysis is a set of statistical processes for estimating the relationships among variables. It includes many techniques for modeling and analyzing several variables, when the focus is on the relationship between a dependent variable and one or more independent variables (or &lsquo;predictors&rsquo;).
For example  Find out the effect of land area and building area on house prices in the Kuningan region (Multiple Linear Regression)
 Find out the effect of allowance and GPA on cum laude predicate (yes or no) ?"/>
<meta name="twitter:site" content="@teamalgoritma"/>

        <meta property="og:title" content="Poisson Regression and Negative Binomial Regression" />
<meta property="og:description" content="Introduction Regression analysis is a set of statistical processes for estimating the relationships among variables. It includes many techniques for modeling and analyzing several variables, when the focus is on the relationship between a dependent variable and one or more independent variables (or &lsquo;predictors&rsquo;).
For example  Find out the effect of land area and building area on house prices in the Kuningan region (Multiple Linear Regression)
 Find out the effect of allowance and GPA on cum laude predicate (yes or no) ?" />
<meta property="og:type" content="article" />
<meta property="og:url" content="/blog/poisson-regression-and-neg-ative-binomial-regression/" />
<meta property="article:published_time" content="2019-10-22T00:00:00&#43;00:00"/>
<meta property="article:modified_time" content="2019-10-22T00:00:00&#43;00:00"/>

        <meta property="og:image" content="//images/logo.png">
        <meta property="og:image:type" content="image/png">
        <meta property="og:image:width" content="512">
        <meta property="og:image:height" content="512">
        
<meta itemprop="name" content="Poisson Regression and Negative Binomial Regression">
<meta itemprop="description" content="Introduction Regression analysis is a set of statistical processes for estimating the relationships among variables. It includes many techniques for modeling and analyzing several variables, when the focus is on the relationship between a dependent variable and one or more independent variables (or &lsquo;predictors&rsquo;).
For example  Find out the effect of land area and building area on house prices in the Kuningan region (Multiple Linear Regression)
 Find out the effect of allowance and GPA on cum laude predicate (yes or no) ?">


<meta itemprop="datePublished" content="2019-10-22T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2019-10-22T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="3108">



<meta itemprop="keywords" content="Machine Learning," />

        

        
            
        

        
        
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800,900|Source+Sans+Pro:400,700">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css">
            <link rel="stylesheet" href="/css/main.css">
            <link rel="stylesheet" href="/css/add-on.css">
            <link rel="stylesheet" href="/css/academicons.min.css">
        

        
            
                
            
                
                    <link rel="stylesheet" href="/css/night-owl.css">
                
            
        


  
    
      <link rel="stylesheet" href="/css/night-owl.css" rel="stylesheet" id="theme-stylesheet">
      <script src="/js/highlight.pack.js"></script>
      <script>hljs.initHighlightingOnLoad();</script>
  


      





    </head>
    <body>

      
      <div id="wrapper">

    
    
<header id="header">
    
      <h1><a href="/">blog</a></h1>
    

    <nav class="links">
        <ul>
            
                <li>
                    <a href="/">
                            <i class="fa fa-home">&nbsp;</i>Home
                    </a>
                </li>
            
                <li>
                    <a href="/tags/machine-learning/">
                            <i class="fa fa-cog">&nbsp;</i>Machine Learning
                    </a>
                </li>
            
                <li>
                    <a href="/tags/data-visualization/">
                            <i class="fa fa-area-chart">&nbsp;</i>Data Visualization
                    </a>
                </li>
            
        </ul>
    </nav>
    <nav class="main">
        <ul>
            
            <li id="share-nav" class="share-menu" style="display:none;">
                <a class="fa-share-alt" href="#share-menu">Share</a>
            </li>
            
            <li class="search">
                <a class="fa-search" href="#search">Search</a>
                <form id="search" method="get" action="//google.com/search">
                    <input type="text" name="q" placeholder="Search" />
                    <input type="hidden" name="as_sitesearch" value="/">
                </form>
            </li>
            <li class="menu">
                <a class="fa-bars" href="#menu">Menu</a>
            </li>
        </ul>
    </nav>
</header>


<section id="menu">

    
        <section>
            <form class="search" method="get" action="//google.com/search">
                <input type="text" name="q" placeholder="Search" />
                <input type="hidden" name="as_sitesearch" value="/">
            </form>
        </section>

    
        <section>
            <ul class="links">
                
                    <li>
                        <a href="/">
                            <h3>
                                <i class="fa fa-home">&nbsp;</i>Home
                            </h3>
                        </a>
                    </li>
                
                    <li>
                        <a href="/tags/machine-learning/">
                            <h3>
                                <i class="fa fa-cog">&nbsp;</i>Machine Learning
                            </h3>
                        </a>
                    </li>
                
                    <li>
                        <a href="/tags/data-visualization/">
                            <h3>
                                <i class="fa fa-area-chart">&nbsp;</i>Data Visualization
                            </h3>
                        </a>
                    </li>
                
            </ul>
        </section>

    
        <section class="recent-posts">
            <div class="mini-posts">
                <header>
                    <h3>Recent Posts</h3>
                </header>
                

                
                    
                

                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/introduction-to-generative-adversarial-network-with-keras/">Introduction to Generative Adversarial Network with Keras</a></h3>
                                
                                <time class="published" datetime=
                                    '2019-12-18'>
                                    December 18, 2019</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/ridge-lasso/">Ridge and LASSO Regression</a></h3>
                                
                                <time class="published" datetime=
                                    '2019-12-18'>
                                    December 18, 2019</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/bio-intro/">Bioinformatics: Decoding Nature&#39;s Code of Life</a></h3>
                                
                                <time class="published" datetime=
                                    '2019-12-02'>
                                    December 2, 2019</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/interpreting-classification-model-with-lime/">Interpreting Classification Model with LIME</a></h3>
                                
                                <time class="published" datetime=
                                    '2019-12-02'>
                                    December 2, 2019</time>
                            </header>
                            

                        </article>
                
                        <article class="mini-post">
                            <header>
                                <h3><a href="/blog/text-lstm/">Text Classification with LSTM</a></h3>
                                
                                <time class="published" datetime=
                                    '2019-11-12'>
                                    November 12, 2019</time>
                            </header>
                            

                        </article>
                

                
                    <a href=
                        
                            /blog/
                        
                        class="button">View more posts</a>
                
            </div>
        </section>

    
        
</section>

    <section id="share-menu">
    <section id="social-share-nav">
        <ul class="links">
            <header>
                <h3>Share this post <i class="fa fa-smile-o"></i></h3>
            </header>
            



<li>
  <a href="https://twitter.com/intent/tweet?text=Poisson%20Regression%20and%20Negative%20Binomial%20Regression&amp;url=%2fblog%2fpoisson-regression-and-neg-ative-binomial-regression%2f" target="_blank" class="share-btn twitter">
    <i class="fa fa-twitter"></i>
    <p>Twitter</p>
    </a>
</li>








<li>
  <a href="https://www.facebook.com/sharer.php?u=%2fblog%2fpoisson-regression-and-neg-ative-binomial-regression%2f" target="_blank" class="share-btn facebook">
    <i class="fa fa-facebook"></i>
    <p>Facebook</p>
    </a>
</li>







<li>
  <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fblog%2fpoisson-regression-and-neg-ative-binomial-regression%2f&amp;title=Poisson%20Regression%20and%20Negative%20Binomial%20Regression" target="_blank" class="share-btn linkedin">
      <i class="fa fa-linkedin"></i>
      <p>LinkedIn</p>
    </a>
</li>











        </ul>
    </section>
</section>

    
    <div id="main">
        
        
        <article class="post">
  <header>
    <div class="title">
        
            <h2><a href="/blog/poisson-regression-and-neg-ative-binomial-regression/">Poisson Regression and Negative Binomial Regression</a></h2>
        
        
    </div>
    <div class="meta">
        

        <time class="published"
            datetime='2019-10-22'>
            October 22, 2019</time>
        <span class="author"><a href="https://github.com/HafizahIlma">Hafizah Ilma</a></span>
        
            <p>15 minute read</p>
        
        
    </div>
</header>


  
    <section id="social-share">
      <ul class="icons">
        



<li>
  <a href="https://twitter.com/intent/tweet?text=Poisson%20Regression%20and%20Negative%20Binomial%20Regression&amp;url=%2fblog%2fpoisson-regression-and-neg-ative-binomial-regression%2f" target="_blank" class="share-btn twitter">
    <i class="fa fa-twitter"></i>
    <p>Twitter</p>
    </a>
</li>








<li>
  <a href="https://www.facebook.com/sharer.php?u=%2fblog%2fpoisson-regression-and-neg-ative-binomial-regression%2f" target="_blank" class="share-btn facebook">
    <i class="fa fa-facebook"></i>
    <p>Facebook</p>
    </a>
</li>







<li>
  <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fblog%2fpoisson-regression-and-neg-ative-binomial-regression%2f&amp;title=Poisson%20Regression%20and%20Negative%20Binomial%20Regression" target="_blank" class="share-btn linkedin">
      <i class="fa fa-linkedin"></i>
      <p>LinkedIn</p>
    </a>
</li>











      </ul>
    </section>
  

  

  <div id="content">
    

<h1 id="introduction">Introduction</h1>

<p>Regression analysis is a set of statistical processes for estimating the relationships among variables. It includes many techniques for modeling and analyzing several variables, when the focus is on the relationship between a dependent variable and one or more independent variables (or &lsquo;predictors&rsquo;).</p>

<h2 id="for-example">For example</h2>

<ol>
<li><p>Find out the <em>effect</em> of land area and building area on house prices in the Kuningan region (Multiple Linear Regression)</p></li>

<li><p>Find out the <em>effect</em> of allowance and GPA on cum laude predicate (yes or no) ? (Binary Logistic Regression)</p></li>

<li><p>Find out the <em>effect</em> of math score and learning program on the number of days in which students are absent from senior high school 123 ?</p></li>
</ol>

<h2 id="some-types-of-regression">Some Types of Regression</h2>

<p><img src="/img/biomial-negatif/pic.png" style="display: block; margin: auto;" /></p>

<h2 id="why-ols-is-not-suitable-for-discrete-data">Why OLS is not Suitable for Discrete Data ?</h2>

<p>Let&rsquo;s see the extreme example below !</p>

<p>Suppose I have data of 20 different visitors who have shopped at store A. Then I want to predict how many times visitors arrive based on the amount of money spent on shopping at store A?</p>

<p>Target variable    (y) : Count of times a visitor arrived</p>

<p>Predictor Variable (x) :
Total costs (Rupiah-Indonesian) incurred for shopping at the store A</p>

<pre><code class="language-r">storeA &lt;- data.frame(visitor=c(2,1,1,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,1),
                    cost=c(52034, 83432, 80241, 52949, 55876, 70292, 30077, 69195, 60991, 46161, 57759, 30648,77724 , 73404, 36850, 42691, 64087, 84858, 70533, 62188))
head(storeA)
</code></pre>

<pre><code>#&gt;   visitor  cost
#&gt; 1       2 52034
#&gt; 2       1 83432
#&gt; 3       1 80241
#&gt; 4       1 52949
#&gt; 5       2 55876
#&gt; 6       2 70292
</code></pre>

<p>I am trying to build a linear regression model using the <code>lm</code> function in R.</p>

<pre><code class="language-r">modelols1 &lt;- lm(visitor~cost, storeA)
summary(modelols1)
</code></pre>

<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = visitor ~ cost, data = storeA)
#&gt; 
#&gt; Residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -0.6809 -0.5033  0.3316  0.4574  0.5600 
#&gt; 
#&gt; Coefficients:
#&gt;               Estimate Std. Error t value Pr(&gt;|t|)    
#&gt; (Intercept)  1.817e+00  4.432e-01   4.100 0.000673 ***
#&gt; cost        -4.444e-06  7.118e-06  -0.624 0.540251    
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 0.5188 on 18 degrees of freedom
#&gt; Multiple R-squared:  0.0212, Adjusted R-squared:  -0.03318 
#&gt; F-statistic: 0.3898 on 1 and 18 DF,  p-value: 0.5403
</code></pre>

<p>From the summary <em>modelols</em> above, it can be seen that <em>modelols</em> has an R-squared of only 2.12% and the variable <code>cost</code> is not significant to the model.</p>

<pre><code class="language-r">plot(storeA$cost, storeA$visitor)
abline(modelols1$coefficients[1], modelols1$coefficients[2], col=&quot;red&quot;)
</code></pre>

<p><img src="/blog/2019-10-22-poisson-regression-and-negative-binomial-regression_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /></p>

<p>The red line in the visualization above is the line of the regression model. And the model formed is</p>

<p><code>$$visitor = 1.817059368-{0.000004444}\times{cost}$$</code></p>

<p>If Ani shopping in shop A with the amount of Rp. 422,000 : then how many times did Ani&rsquo;s prediction come?</p>

<pre><code class="language-r">predict(modelols1, data.frame(cost=c(422000)))
</code></pre>

<pre><code>#&gt;           1 
#&gt; -0.05814847
</code></pre>

<p>Based on the prediction results above, Ani came to shop A is -0.6 times.
Does it make sense ?</p>

<h1 id="poisson-regression">Poisson Regression</h1>

<p>In statistics, Poisson regression is a generalized linear model form of regression analysis used to model count data and contingency tables. Poisson regression assumes the response variable Y has a Poisson distribution, and assumes the logarithm of its expected value can be modeled by a linear combination of unknown parameters. A Poisson regression model is sometimes known as a log-linear model, especially when used to model contingency tables.</p>

<p>Poisson regression models are generalized linear models with the logarithm as the (canonical) link function, and the Poisson distribution function as the assumed probability distribution of the response.</p>

<h2 id="where-poisson-regression-is-applicable">Where Poisson Regression is Applicable?</h2>

<p><em>1. The target variable is taking positive integer values like :</em></p>

<ul>
<li><p>Count of complete network failure in a year for a big size tech firm.</p></li>

<li><p>Number of families visiting a restaurant in a giver hour.</p></li>

<li><p>Number of accident claims being made by car insurance holder in a year.</p></li>

<li><p>Expected number of credit cards a customer may have?</p></li>
</ul>

<p><em>2. Please note in all these cases, outcome can be:</em></p>

<ul>
<li><p>0</p></li>

<li><p>1</p></li>

<li><p>2</p></li>

<li><p>3</p></li>

<li><p>..(only positive integer outcome is posible)</p></li>
</ul>

<p>*3. And most of the time dependent variable is smaller values like 0,1,2 and there are few somewhat larger values, so the average is small value *</p>

<p>*4. In such cases the target variabel Y has a Poisson Distribution  *</p>

<ul>
<li><p>Numerical</p></li>

<li><p>Categorical</p></li>
</ul>

<p>*5. If the average is large value, then for the target variabel (y), the normal distribution is a good approximation for the Poissson distribution *</p>

<h2 id="assumption-of-poisson-regression">Assumption of Poisson Regression</h2>

<ul>
<li><p>The dependent variable y is count</p></li>

<li><p>Counts must be positive integers (i.e. 0,1,2,..,k)</p></li>

<li><p>Counts must follow a Poisson Distribution. Therefore, the <em>mean = variance</em>.</p></li>

<li><p>Explanatory variables must be continuous, dichotomous or ordinal.</p></li>

<li><p>Observation are independent of each other.</p></li>
</ul>

<h2 id="in-case-of-poisson-distribution">In case of Poisson Distribution</h2>

<ul>
<li>The probability of dependent variable y, taking value k (i.e. count=k) is given by:</li>
</ul>

<p><code>$$P(k\:events\:in\:interval) = e^{-\lambda}\frac{\lambda^k}{k!}$$</code></p>

<p>Where :</p>

<ul>
<li><p>(\lambda)  is the rate of event or average count of events per interval</p></li>

<li><p><code>\(e = 2.71828\)</code></p></li>

<li><p><code>\(k! = {k}\times{(k-1)}\times{(k-2)}\times.....\times1\)</code></p></li>
</ul>

<h2 id="an-example-of-poisson-distribution">An Example of Poisson Distribution</h2>

<p><code>$$P(k\:events\:in\:interval) = e^{-\lambda} \frac{\lambda^k}{k!}$$</code></p>

<ul>
<li><p>If defect rate for a manufacturer is 5%, then</p></li>

<li><p>What is the probability that in a consignment of 100 TV</p></li>

<li><p>Q : There will be no defect at all?</p></li>

<li><p>A : here (\lambda)  is 5</p></li>

<li><p><code>\(P(0)=e^{-5}\)</code></p></li>

<li><p>If Poisson regression gives: <code>\(\hat{y} = ln(y) = a + bx\)</code></p></li>

<li><p>Then please <code>\(\frac{5^0}{0!}\)</code></p></li>

<li><p>Q : There will be one defect only?</p></li>

<li><p>A : <code>\(P(1)=e^{-5}\frac{5^1}{1!}\)</code></p></li>
</ul>

<h2 id="process-of-poisson-regression-model-development">Process of Poisson Regression Model Development</h2>

<ul>
<li><p>If you have count as the dependent variabel y,</p></li>

<li><p><code>\(\hat{y} = ln(y)\)</code> can be taken to develop a regression model (i.e. Poisson Regression)</p></li>

<li><p>MLE (Maximum Likelihood Estimation) is used to estimate the parameters of regression equation
understand :</p>

<ul>
<li><p>if <code>\(b=0\)</code>, then <code>\(\hat{y} =a\)</code> i.e. ln(y)=a, hence <strong>expected/predicted
<code>\(\hat{y} = exp(a)\)</code></strong></p></li>

<li><p>If <code>\({b}\neq{0}\)</code> , then <code>\(\hat{y}\)</code> i.e. <code>\(ln(y)=a + bx\)</code>, hence predicted</p></li>
</ul></li>
</ul>

<p><code>$$\hat{y} = exp(a+bx) = exp(a) \times {exp(bx)}$$</code></p>

<ul>
<li><p>One unit of x increase, will change y by exp(b) <strong>times</strong> (note : <strong>Multiplicative</strong> impact not the <em>addition</em> impact that happens in linear regression case).</p></li>

<li><p>If b&gt;0, then y will become greater by exp(b) times.</p></li>

<li><p>Like if <code>\(b=2\)</code>, then y will become bigger with each unit increase of x, by exp(2) times.</p></li>

<li><p>And similary if <code>\(b&lt;0\)</code> (like <code>\(b=2\)</code>), then y will decrease with each unit increase of x, by <code>\(exp(-2)\)</code> times.</p></li>
</ul>

<h1 id="negative-binomial-regression">Negative Binomial Regression</h1>

<p>Negative binomial regression is a popular generalization of Poisson regression because it loosens the highly restrictive assumption that the variance is equal to the mean made by the Poisson model. The traditional negative binomial regression model, commonly known as NB2, is based on the Poisson-gamma mixture distribution. This model is popular because it models the Poisson heterogeneity with a gamma distribution.</p>

<p><strong>Basic assumption for Poisson Regression : mean=variance &ndash;&gt; equidispersi</strong></p>

<ul>
<li><p>variance &lt; mean &ndash;&gt; Undispersion</p></li>

<li><p><em>variance &gt; mean &ndash;&gt; Overdispersion</em></p></li>
</ul>

<p>To overcome the Overdispersion problem, one alternative is to use <em>Negative Binomial Regression</em>.</p>

<p><em>Negative Binomial Regression is a special regression of Poisson regression that occurs Overdispersion.</em></p>

<h1 id="study-case">Study Case</h1>

<p><strong>An administrator at a school 123 wants to learn about student absence behavior. Look for the effect of the number of days of absence based on the type of student program and mathematics score</strong></p>

<h2 id="read-data">Read Data</h2>

<p>The first step taken is reading the data. Use the <code>read.dta</code> function from the<code>foreign</code> library. The data used comes from the link &ldquo;<a href="https://stats.idre.ucla.edu/stat/stata/dae/nb_data.dta&quot;">https://stats.idre.ucla.edu/stat/stata/dae/nb_data.dta&quot;</a></p>

<pre><code class="language-r">dat &lt;- read.dta(&quot;https://stats.idre.ucla.edu/stat/stata/dae/nb_data.dta&quot;)
head(dat)
</code></pre>

<pre><code>#&gt;     id gender math daysabs prog
#&gt; 1 1001   male   63       4    2
#&gt; 2 1002   male   27       4    2
#&gt; 3 1003 female   20       2    2
#&gt; 4 1004 female   16       3    2
#&gt; 5 1005 female    2       3    2
#&gt; 6 1006 female   71      13    2
</code></pre>

<p>daysabs : The number of days of absence (Discreate - Positive)
The value of the daysabs variable cannot be negative. The dayabs variable is positive integer value</p>

<p>math : Math score (kontinu)</p>

<p>program (prog): Student program (Categorical)</p>

<ul>
<li><p>1 : General,</p></li>

<li><p>2 : Academic,</p></li>

<li><p>3 : Vocational</p></li>
</ul>

<p>Choose 3 variables to be used are math, daysabs, and prog (based on study case)</p>

<pre><code class="language-r">dat &lt;- dat[,c(3:5)]
dat$prog &lt;-  factor(dat$prog, levels = 1:3, labels = c(&quot;General&quot;, &quot;Academic&quot;, &quot;Vocational&quot;))
summary(dat$daysabs)
</code></pre>

<pre><code>#&gt;    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#&gt;   0.000   1.000   4.000   5.955   8.000  35.000
</code></pre>

<h2 id="distribution-of-days-absent-in-each-program">Distribution of days absent in each program.</h2>

<pre><code class="language-r">ggplot(dat, aes(daysabs, fill = prog)) + geom_histogram(binwidth = 1, breaks=1:90) + facet_grid(prog ~ 
    ., margins = TRUE, scales = &quot;free&quot;)
</code></pre>

<p><img src="/blog/2019-10-22-poisson-regression-and-negative-binomial-regression_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" />
In the plots above is a distribution of each program has 314 observations and the distribution seems quite reasonable. The average of our outcome variables is much lower than the variance. It can be seen that the accumulation of data is close to 0, this condition indicates the data are overdispersion. There is no negative data. Because the number of days of absence cannot be negative.</p>

<h2 id="build-the-model">Build the Model</h2>

<p>Poisson regression modeling in R uses the <code>glm</code> function, with parameters:</p>

<ul>
<li><p>formula: y~x</p></li>

<li><p>family: &ldquo;poisson&rdquo;</p></li>

<li><p>data: data</p></li>
</ul>

<p><strong>If I want to build a model to predict daysabs without any predictor variable using Poisson Regression</strong></p>

<pre><code class="language-r">model1 &lt;- glm(daysabs ~1, family = &quot;poisson&quot;, data = dat)
summary(model1)
</code></pre>

<pre><code>#&gt; 
#&gt; Call:
#&gt; glm(formula = daysabs ~ 1, family = &quot;poisson&quot;, data = dat)
#&gt; 
#&gt; Deviance Residuals: 
#&gt;     Min       1Q   Median       3Q      Max  
#&gt; -3.4512  -2.5184  -0.8525   0.7957   8.1169  
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)  1.78430    0.02312   77.16   &lt;2e-16 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for poisson family taken to be 1)
#&gt; 
#&gt;     Null deviance: 2217.7  on 313  degrees of freedom
#&gt; Residual deviance: 2217.7  on 313  degrees of freedom
#&gt; AIC: 3103
#&gt; 
#&gt; Number of Fisher Scoring iterations: 5
</code></pre>

<p>The Coefficients intercept is 1.784. Recall, writing the Poisson regression model formula:
$$ \hat{y} = exp(a+bx) = {exp(a)}\times{exp(bx)}$$</p>

<p>Our model1 : $$ \hat{y} = exp(a) = exp(1.784)$$</p>

<pre><code class="language-r">exp(model1$coefficients[1])
</code></pre>

<pre><code>#&gt; (Intercept) 
#&gt;    5.955414
</code></pre>

<pre><code class="language-r">mean(dat$daysabs)
</code></pre>

<pre><code>#&gt; [1] 5.955414
</code></pre>

<p>From the result above, exp(intercept) is mean of the target variable (daysabs)</p>

<p><strong>If I want to predict daysabs based on math scores and student programs with Poisson Regression</strong></p>

<pre><code class="language-r">modelpois &lt;- glm(daysabs ~ math + prog, family = &quot;poisson&quot;, data = dat)
summary(modelpois)
</code></pre>

<pre><code>#&gt; 
#&gt; Call:
#&gt; glm(formula = daysabs ~ math + prog, family = &quot;poisson&quot;, data = dat)
#&gt; 
#&gt; Deviance Residuals: 
#&gt;     Min       1Q   Median       3Q      Max  
#&gt; -4.2597  -2.2038  -0.9193   0.6511   7.4233  
#&gt; 
#&gt; Coefficients:
#&gt;                 Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)     2.651974   0.060736  43.664  &lt; 2e-16 ***
#&gt; math           -0.006808   0.000931  -7.313 2.62e-13 ***
#&gt; progAcademic   -0.439897   0.056672  -7.762 8.35e-15 ***
#&gt; progVocational -1.281364   0.077886 -16.452  &lt; 2e-16 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for poisson family taken to be 1)
#&gt; 
#&gt;     Null deviance: 2217.7  on 313  degrees of freedom
#&gt; Residual deviance: 1774.0  on 310  degrees of freedom
#&gt; AIC: 2665.3
#&gt; 
#&gt; Number of Fisher Scoring iterations: 5
</code></pre>

<p>From the summary(modelpois) above,
We get the Poisson model: $$ \hat{daysabs} = exp(2.651974-0.006808math-0.439897progAcademic-1.281364progVocational)$$</p>

<p>Intercept, math, progAcademic, and progVocational are significant to the model.</p>

<p>And the AIC (Akaike Information Criterion) value is 2665.3</p>

<h2 id="equidispersion-assumption">Equidispersion Assumption</h2>

<p>Base assumption of Poisson regression is **Equidispersion ** : <em>No Overdispersion</em> or <em>No Undispersion</em></p>

<p>Equidispersion occurs if the Dispersion parameter approaches 1.</p>

<pre><code class="language-r">library(DHARMa)
resp &lt;- simulateResiduals(modelpois, refit = T)
testDispersion(resp, plot = F)
</code></pre>

<pre><code>#&gt; 
#&gt;  DHARMa nonparametric dispersion test via mean deviance residual
#&gt;  fitted vs. simulated-refitted
#&gt; 
#&gt; data:  resp
#&gt; dispersion = 6.5899, p-value &lt; 2.2e-16
#&gt; alternative hypothesis: two.sided
</code></pre>

<p>Based on the results above, we got the <em>dispersion</em> value is 6.5899. That means our data is overdispersion (variance is greater than average). Because the dispersion value far exceeds one. Otherwise, if our dispersion value is far below one, then our data is undispersion (variance value is smaller than average).</p>

<p>On this occasion, I only discussed when data is overdispersion. Because generally overdispersion is more common than undispersion</p>

<pre><code class="language-r">plot(resp)
</code></pre>

<p><img src="/blog/2019-10-22-poisson-regression-and-negative-binomial-regression_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;" />
Look at the Q-Q plot residuals. The plot above is a residual plot whether spreads normally or not. When the residual points have followed the diagonal line, then the residuals are normally distributed.</p>

<p>However, Q-Q plot residuals from the Poisson regression model above show that residuals do not follow the normal distribution</p>

<h2 id="overdispersion-assumption">Overdispersion Assumption</h2>

<p>Because our data has overdispersion (offense of dispersion assumption). Then the alternative is to use <em>Negative Binomial Regression</em>.</p>

<p>Build a Binomial Negative Regression model in R using the <code>glm.nb</code> function from the library <code>car</code>.</p>

<pre><code class="language-r">modelnb1 &lt;- glm.nb(daysabs ~ 1, data = dat)
summary(modelnb1)
</code></pre>

<pre><code>#&gt; 
#&gt; Call:
#&gt; glm.nb(formula = daysabs ~ 1, data = dat, init.theta = 0.7999836134, 
#&gt;     link = log)
#&gt; 
#&gt; Deviance Residuals: 
#&gt;     Min       1Q   Median       3Q      Max  
#&gt; -1.8476  -1.0921  -0.3107   0.2621   2.1384  
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)   1.7843     0.0672   26.55   &lt;2e-16 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for Negative Binomial(0.8) family taken to be 1)
#&gt; 
#&gt;     Null deviance: 357.49  on 313  degrees of freedom
#&gt; Residual deviance: 357.49  on 313  degrees of freedom
#&gt; AIC: 1796.9
#&gt; 
#&gt; Number of Fisher Scoring iterations: 1
#&gt; 
#&gt; 
#&gt;               Theta:  0.8000 
#&gt;           Std. Err.:  0.0758 
#&gt; 
#&gt;  2 x log-likelihood:  -1792.9450
</code></pre>

<p>For the results of Negative Binomial Regression when not using any predictor in the model, it can be seen when using Poisson regression and negative binomial regression the estimated intercept is the same value.</p>

<h2 id="negative-binomial-regression-1">Negative Binomial Regression</h2>

<p><strong>We want to predict daysabs based on math scores and student programs using Negative Binomial Regression</strong></p>

<pre><code class="language-r">modelnb &lt;- glm.nb(daysabs ~ math + prog, data = dat)
summary(modelnb)
</code></pre>

<pre><code>#&gt; 
#&gt; Call:
#&gt; glm.nb(formula = daysabs ~ math + prog, data = dat, init.theta = 1.032713156, 
#&gt;     link = log)
#&gt; 
#&gt; Deviance Residuals: 
#&gt;     Min       1Q   Median       3Q      Max  
#&gt; -2.1547  -1.0192  -0.3694   0.2285   2.5273  
#&gt; 
#&gt; Coefficients:
#&gt;                 Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)     2.615265   0.197460  13.245  &lt; 2e-16 ***
#&gt; math           -0.005993   0.002505  -2.392   0.0167 *  
#&gt; progAcademic   -0.440760   0.182610  -2.414   0.0158 *  
#&gt; progVocational -1.278651   0.200720  -6.370 1.89e-10 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for Negative Binomial(1.0327) family taken to be 1)
#&gt; 
#&gt;     Null deviance: 427.54  on 313  degrees of freedom
#&gt; Residual deviance: 358.52  on 310  degrees of freedom
#&gt; AIC: 1741.3
#&gt; 
#&gt; Number of Fisher Scoring iterations: 1
#&gt; 
#&gt; 
#&gt;               Theta:  1.033 
#&gt;           Std. Err.:  0.106 
#&gt; 
#&gt;  2 x log-likelihood:  -1731.258
</code></pre>

<p>From the summary(modelnb) above,
we get the Negative Binomial model: $$ \hat{daysabs} = exp(2.615265   -0.005993math-0.440760progAcademic-1.278651progVocational)$$</p>

<p>Intercept, math, progAcademic, and progVocational are significant to the model.</p>

<p>And the AIC (Akaike Information Criterion) value is 1741.3</p>

<pre><code class="language-r">#Negative Binomial
resnb &lt;- simulateResiduals(modelnb, refit = T)
plot(resnb)
</code></pre>

<p><img src="/blog/2019-10-22-poisson-regression-and-negative-binomial-regression_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;" /></p>

<p>In the Q-Q Plot Residuals above, it can be seen that the residual point has followed a diagonal line (almost perfect). Therefore the residuals are normally distributed.</p>

<pre><code class="language-r">testDispersion(resnb, plot=F)
</code></pre>

<pre><code>#&gt; 
#&gt;  DHARMa nonparametric dispersion test via mean deviance residual
#&gt;  fitted vs. simulated-refitted
#&gt; 
#&gt; data:  resnb
#&gt; dispersion = 1.0913, p-value = 0.216
#&gt; alternative hypothesis: two.sided
</code></pre>

<p>From the results of the parameter dispersion above, it can be seen that the parameter dispersion value is 1.0913 already close to 1. It means that the Negative Binomial Regression model can reduce the overdispersion problem.</p>

<h2 id="the-best-model-comparison">The Best Model Comparison</h2>

<ul>
<li><em>Comparison of AIC values</em></li>
</ul>

<pre><code class="language-r">modelpois$aic 
</code></pre>

<pre><code>#&gt; [1] 2665.285
</code></pre>

<pre><code class="language-r">modelnb$aic 
</code></pre>

<pre><code>#&gt; [1] 1741.258
</code></pre>

<p>Compare the models, the Poisson Regression model and the Negative Binomial Regression model based on the AIC value. Then the Negative Binomial Regression model is the model with the smallest AIC value.</p>

<ul>
<li><em>Comparison Dispersion Parameters</em></li>
</ul>

<p>Dispersion (Poisson Regression) value : 6.5899</p>

<p>Dispersion (Negative Binomial Regression) value  : 1.0913</p>

<p>Based on the value of the dispersion parameters of the two models above, it can be seen the Negative Binomial Regression
model that has a dispersion value close to 1.</p>

<ul>
<li><em>Comparison The Residuals</em></li>
</ul>

<p>The comparison of residuals based on the Q-Q plot residuals, the residuals Binomial Negative regression model is obtained which has a normally distributed residual.</p>

<h2 id="model-interpretation">Model Interpretation</h2>

<p>Based on the explanation above, the best model chosen is the <em>Binomial Negative Regression</em> model.</p>

<p>Negative Binomial model: $$ \hat{daysabs} = exp(2.615265   -0.005993math-0.440760progAcademic-1.278651progVocational)$$</p>

<p><em>or</em> : $$ \hat{daysabs} = exp(2.615265)*exp(-0.005993*math)*exp(-0.440760*progAcademic)*exp(-1.278651*progVocational)$$</p>

<pre><code class="language-r">(estnb &lt;- cbind(Estimate = coef(modelnb)))
</code></pre>

<pre><code>#&gt;                    Estimate
#&gt; (Intercept)     2.615265446
#&gt; math           -0.005992988
#&gt; progAcademic   -0.440760012
#&gt; progVocational -1.278650721
</code></pre>

<pre><code class="language-r">exp(estnb)
</code></pre>

<pre><code>#&gt;                  Estimate
#&gt; (Intercept)    13.6708448
#&gt; math            0.9940249
#&gt; progAcademic    0.6435471
#&gt; progVocational  0.2784127
</code></pre>

<ul>
<li><p><strong>Every one-unit increase in the value of math, then daysabs(y) will decrease (-) by 0.9940249 times, provided that other predictor variables are constant</strong></p></li>

<li><p><strong>If a student is an academic program, then daysabs(y) will decrease (-) by 0.6435471 times compared to if the student is a general program, provided that other predictor variables are constant</strong></p></li>

<li><p><strong>If a student is an Vocational program, then daysabs(y) will decrease (-) by 0.2784127 times compared to if the student is a general program, provided that other predictor variables are constant</strong></p></li>
</ul>

<h2 id="predicted-value">Predicted Value</h2>

<p><em>Proof :</em></p>

<p><strong>&ldquo;Every one-unit increase in the value of math, then daysabs(y) will decrease (-) by 0.9940249 times, provided that other predictor variables are constant&rdquo;</strong></p>

<p>If Ani and Budi are general program students and have math grades 97 and 96, then how many days are they absent?</p>

<pre><code class="language-r">daysabs.Ani &lt;- exp(2.615265-0.005993*97)
daysabs.Budi &lt;- exp(2.615265-0.005993*96)
daysabs.Ani 
</code></pre>

<pre><code>#&gt; [1] 7.644176
</code></pre>

<pre><code class="language-r">daysabs.Budi
</code></pre>

<pre><code>#&gt; [1] 7.690125
</code></pre>

<pre><code class="language-r">daysabs.Ani2 &lt;- daysabs.Budi*0.9940249

daysabs.Ani 
</code></pre>

<pre><code>#&gt; [1] 7.644176
</code></pre>

<pre><code class="language-r">daysabs.Ani2
</code></pre>

<pre><code>#&gt; [1] 7.644175
</code></pre>

<p>From the results above it is proven that : <strong>&ldquo;Every one-unit increase in the value of math, then daysabs(y) will decrease (-) by 0.9940249 times, provided that other predictor variables are constant&rdquo;</strong></p>

<p>If I make a new data frame with 3 observations and have a different program.
Look for the predicted daysabs value based on the new data.</p>

<pre><code class="language-r">newdata1 &lt;- data.frame(math = mean(dat$math), prog = factor(1:3, levels = 1:3, labels = levels(dat$prog)))
</code></pre>

<p>type = &ldquo;link&rdquo; produces a predict value in the form of &ldquo;log&rdquo;.</p>

<pre><code class="language-r">newdata1$pred &lt;- predict(modelnb, newdata1, type = &quot;link&quot;)
newdata1
</code></pre>

<pre><code>#&gt;       math       prog     pred
#&gt; 1 48.26752    General 2.325999
#&gt; 2 48.26752   Academic 1.885239
#&gt; 3 48.26752 Vocational 1.047348
</code></pre>

<p>type = &ldquo;response&rdquo;  generate predictive value that has been exponential &ldquo;exp&rdquo;.</p>

<pre><code class="language-r">newdata1$pred &lt;- predict(modelnb, newdata1, type = &quot;response&quot;)
newdata1
</code></pre>

<pre><code>#&gt;       math       prog      pred
#&gt; 1 48.26752    General 10.236899
#&gt; 2 48.26752   Academic  6.587927
#&gt; 3 48.26752 Vocational  2.850083
</code></pre>

<pre><code class="language-r">exp(estnb)
</code></pre>

<pre><code>#&gt;                  Estimate
#&gt; (Intercept)    13.6708448
#&gt; math            0.9940249
#&gt; progAcademic    0.6435471
#&gt; progVocational  0.2784127
</code></pre>

<pre><code class="language-r">#academic dan general
10.236899*0.6435471 #academic
</code></pre>

<pre><code>#&gt; [1] 6.587927
</code></pre>

<pre><code class="language-r">#vocational dan general
10.236899*0.2784127
</code></pre>

<pre><code>#&gt; [1] 2.850083
</code></pre>

<p>From the results above it is proven that :</p>

<ul>
<li><p><strong>If a student is an academic program, then daysabs(y) will decrease (-) by 0.6435471 times compared to if the student is a general program, provided that other predictor variables are constant</strong></p></li>

<li><p><strong>If a student is an Vocational program, then daysabs(y) will decrease (-) by 0.2784127 times compared to if the student is a general program, provided that other predictor variables are constant</strong></p></li>
</ul>

  </div>

  <footer>
    <ul class="stats">
  <li class="categories">
    <ul>
        
            
            
                <i class="fa fa-folder"></i>
                
                
                <li><a class="article-category-link" href="/categories/r">R</a></li>
                
            
        
    </ul>
  </li>
  <li class="tags">
    <ul>
        
            
            
                <i class="fa fa-tags"></i>
                
                
                <li><a class="article-category-link" href="/tags/machine-learning">Machine Learning</a></li>
                
            
        
    </ul>
  </li>
</ul>

  </footer>

</article>

    <article class="post">
        <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "https-algotech-netlify-com" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </article>


<ul class="actions pagination">
    
        <li><a href="/blog/tidymodels/"
                class="button big previous">Introduction to tidymodels</a></li>
    

    
        <li><a href="/blog/text-lstm/"
                class="button big next">Text Classification with LSTM</a></li>
    
</ul>


    </div>
    
<section id="sidebar">

  
  <section id="intro">
    
    
      
        <a href='/'><img src="/img/main/logo.png" class="intro-circle" width="30%" alt="Hugo Future Imperfect" /></a>
      
    
    
      <header>
        <h2>Algoritma Technical Blog</h2>
        <p>We're a group of people who teach data science to individuals, trains companies and their employees to better profit from data. We care about the development of data science and a sense of community that connects our alumni and team with one another. To learn more about our approach to data science problems, feel free to hop over to our blog.</p>
      </header>
    
    
      <ul class="icons">
        
        
  <li><a href="//github.com/teamalgoritma" target="_blank" title="GitHub" class="fa fa-github"></a></li>



























  <li><a href="//linkedin.com/company/teamalgoritma" target="_blank" title="LinkedIn Company" class="fa fa-linkedin"></a></li>









  <li><a href="//facebook.com/teamalgoritma" target="_blank" title="Facebook" class="fa fa-facebook"></a></li>





















  <li><a href="//instagram.com/teamalgoritma" target="_blank" title="Instagram" class="fa fa-instagram"></a></li>





  <li><a href="//twitter.com/teamalgoritma" target="_blank" title="Twitter" class="fa fa-twitter"></a></li>




















      </ul>
    
  </section>



  
  
  

  
  

  
  <section id="footer">
    <p class="copyright">
      
        &copy; 2019
        
          Algoritma Technical Blog
        
      .
      Powered by <a href="//gohugo.io" target="_blank">Hugo</a>
    </p>
  </section>
</section>

    </div>
    <a id="back-to-top" href="#" class="fa fa-arrow-up fa-border fa-2x"></a>
    

    
      
    

    
      
      
      
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>
        
        
        
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/r.min.js"></script>
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/yaml.min.js"></script>
        <script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/css.min.js"></script>
        <script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>
      
    
    
    
      <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/skel/3.0.1/skel.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js"></script>
      <script src="/js/util.js"></script>
      <script src="/js/main.js"></script>
      <script src="/js/backToTop.js"></script>
    

    
      
        
      
        
          <script src="/js/bootstrap.min.js"></script>
        
      
    

    
    <script>hljs.initHighlightingOnLoad();</script>
      <script src="//yihui.name/js/math-code.js"></script>
<script async
src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>


  </body>
</html>

